<?php

namespace Container0bUQtux;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OLySUtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._OLySUt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._OLySUt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservationrepa' => ['privates', '.errored..service_locator._OLySUt.App\\Entity\\Reservationrepas', NULL, 'Cannot autowire service ".service_locator._OLySUt": it references class "App\\Entity\\Reservationrepas" but no such service exists.'],
        ], [
            'reservationrepa' => 'App\\Entity\\Reservationrepas',
        ]);
    }
}
