<?php

namespace Container0bUQtux;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationrepasService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._OLySUt.App\Entity\Reservationrepas' shared service.
     *
     * @return \App\Entity\Reservationrepas
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._OLySUt": it references class "App\\Entity\\Reservationrepas" but no such service exists.');
    }
}
