<?php

namespace ContainerHM0D7ZY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HVwMxnyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hVwMxny' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hVwMxny'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservationrepasRepository' => ['privates', 'App\\Repository\\ReservationrepasRepository', 'getReservationrepasRepositoryService', true],
        ], [
            'reservationrepasRepository' => 'App\\Repository\\ReservationrepasRepository',
        ]);
    }
}
