<?php

namespace ContainerHM0D7ZY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3aTd9kzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3aTd9kz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3aTd9kz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repasRepository' => ['privates', 'App\\Repository\\RepasRepository', 'getRepasRepositoryService', true],
        ], [
            'repasRepository' => 'App\\Repository\\RepasRepository',
        ]);
    }
}
