<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHM0D7ZY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHM0D7ZY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHM0D7ZY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHM0D7ZY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHM0D7ZY\App_KernelDevDebugContainer([
    'container.build_hash' => 'HM0D7ZY',
    'container.build_id' => 'f892fac4',
    'container.build_time' => 1615536487,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHM0D7ZY');
